# Generated by Django 4.2.4 on 2023-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='ticker',
            field=models.CharField(max_length=25),
        ),
    ]
