# Generated by Django 4.2.4 on 2023-09-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_watchlist_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
